### ISSUE TITLE
installer detected as a virus

### ISSUE THREAD

**Issue by mvivaldi** [Jawesome99/IW4x#6]
If I try to download the installer, windows inform me that it contains a virus:
Trojan:Win32/Woreflint.A!cl
the installer_legacy works as expected

**Comment by Emosewaj** [comment]
The GUI installer being detected as a virus is a false positive.

This is caused by the Google API's DLL file being included in the installer.exe to create a single executable file instead of having to install it because there's one DLL that isn't included in the file.

The false positive can be savely ignored.

**Comment by mvivaldi** [comment]
Ok,
I suggest to write something in the readme.
Thank you!
